### ISSUE TITLE
Correções ATM

### ISSUE THREAD

**Issue by gabrieltosta96** [robertorj7/atm-heroway#1]
Você poderia implementar o `let` da variavel aqui ao invés de inicializar lá na linha `27` com o valor `0`.
Isso vale para todas as outras variaveis. Ok?
https://github.com/robertorj7/atm-heroway/blob/6f517db053add66936ccb232e07214958b6b1eed/scripts/index.js#L39

Considerações finais:
Cara, seu código está muito bom, sinceramente não tem muito o que eu comentar.
Achei muito legal sua implementação com sem o uso de um `while`. Parabéns!

**Comment by robertorj7** [comment]
Tem razão, não havia necessidade de inicializar as variáveis.
Obrigado Gabriel!
